CREATE DATABASE Test;
GO
-- DROP DATABASE Test

USE Test;

CREATE TABLE [User]
(
  Id INT PRIMARY KEY IDENTITY(1,1),
  Username VARCHAR(30) NOT NULL UNIQUE,
  Password VARCHAR(30) NOT NULL,
  Firstname VARCHAR(30) NOT NULL,
  Lastname VARCHAR(30) NOT NULL,
  Phone VARCHAR(12) NULL,
  Email VARCHAR(255) NULL,
  IsReviewer bit NOT NULL,
  IsAdmin bit NOT NULL
)


CREATE TABLE Vendor
(
  Id INT PRIMARY KEY IDENTITY(1,1),
  Code VARCHAR(30) NOT NULL UNIQUE,
  Name VARCHAR(30) NOT NULL,
  Address VARCHAR(30) NOT NULL,
  City VARCHAR(30) NOT NULL,
  State VARCHAR(2) NOT NULL,
  Zip CHAR(5) NOT NULL,
  Phone VARCHAR(12) NULL,
  Email VARCHAR(255) NULL
)

CREATE TABLE Product
(
  Id INT PRIMARY KEY IDENTITY(1,1),
  PartNbr VARCHAR(30) NOT NULL UNIQUE,
  Name VARCHAR(30) NOT NULL,
  Price DECIMAL(11,2) NOT NULL,
  Unit VARCHAR(30) NOT NULL,
  PhotoPath VARCHAR(30) NULL,
  VendorId INT REFERENCES Vendor(Id)
)

CREATE TABLE Request
(
  Id INT PRIMARY KEY IDENTITY(1,1),
  Description VARCHAR(80) NOT NULL,
  Justification VARCHAR(80) NOT NULL,
  RejectionReason VARCHAR(80) NULL,
  DeliveryMode VARCHAR(20) NOT NULL DEFAULT 'Pickup',
  Status VARCHAR(10) NOT NULL DEFAULT 'NEW',
  Total DECIMAL(11,2) NOT NULL DEFAULT 0,
  UserId INT NOT NULL REFERENCES [User](Id)
)

CREATE TABLE RequestLine
(
  Id INT PRIMARY KEY IDENTITY(1,1),
  RequestId INT NOT NULL REFERENCES Request(Id),
  ProductId INT NOT NULL REFERENCES Product(Id),
  Quantity INT NOT NULL DEFAULT 1
)

